{% for operation in operations %}
    /**
{% if operation.description %}     * {{ operation.description }}
     *
{% endif %}
{% for name, arg in operation.arguments %}     * @param {{ arg.docType }}{% if arg.optional %}|null{% endif %} ${{ name }}
{% endfor %}
     * @return {% if operation.return %}{{ operation.return.docType }}{% else %}void{% endif %}

{% for throw in operation.throws %}     * @throws {{ throw.docType }}Exception
{% endfor %}
     * @throws ClientException
     */
    public function {{ operation.methodName }}({% for name, arg in operation.arguments %}{% if arg.optional %}?{% endif %}{{ arg.type }} ${{ name }}{% if arg.optional %} = null{% endif %}{% if not loop.last %}, {% endif %}{% endfor %}): {% if operation.return %}{{ operation.return.type }}{% else %}void{% endif %}

    {
        $url = $this->parser->url('{{ operation.path|raw }}', [
{% for name in operation.pathNames %}
            '{{ name }}' => ${{ name }},
{% endfor %}
        ]);

        $options = [
            'query' => $this->parser->query([
{% for name in operation.queryNames %}
                '{{ name }}' => ${{ name }},
{% endfor %}
            ]),
{% if operation.bodyName is not null %}
            'json' => ${{ operation.bodyName }}
{% endif %}
        ];

        try {
            $response = $this->httpClient->request('{{ operation.method }}', $url, $options);
            $data = (string) $response->getBody();

{% if operation.return %}
            return $this->parser->parse($data, {{ operation.return.type }}::class);
{% endif %}
        } catch (BadResponseException $e) {
            $data = (string) $e->getResponse()->getBody();

            switch ($e->getResponse()->getStatusCode()) {
{% for code, return in operation.throws %}
                case {{ code }}:
                    throw new {{ return.type }}Exception($this->parser->parse($data, {{ return.type }}::class));
{% endfor %}
                default:
                    throw new UnknownStatusCodeException('The server returned an unknown status code');
            }
        } catch (\Throwable $e) {
            throw new ClientException('An unknown error occurred: ' . $e->getMessage());
        }
    }

{% endfor %}
